version: '3'
services:
  front:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: client-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    volumes:
      - ./client:/app
    depends_on:
      - backend
    
  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: server-container
    networks:
      - mern-stack-network
    volumes:
      - ./server:/app
    environment:
      - TOKEN_SECRET_KEY=saurabh
      - TMDB_BASE_URL=https://api.themoviedb.org/3/
      - TMDB_KEY=066b9b73270a351cecbf318faaa9122a
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGODB_URL=mongodb+srv://saurabhmaurya8626:FZWMkNHN3i3sDIjM@mern-movie.ppsagny.mongodb.net/movie-app?retryWrites=true&w=majority
      
  
networks:
  mern-stack-network:
volumes:
  mongoData: